# Starter pipeline
name: 1.0.2.$(rev:r)
variables: 
- name: Project.Path
  value: '**/PolyhydraGames.RetroAchievements.csproj'
- name: BuildConfiguration
  value: Release
- name: CDN_PATH
  value: '/data/api_retroachievements' 
trigger:
  branches:
    include:
    - refs/heads/main 

jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self

  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '$(Project.Path)' 
      versioningScheme: 'byBuildNumber'
      arguments: '-c $(BuildConfiguration)' 

  - task: DotNetCoreCLI@2
    enabled: false
    inputs:
     
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget.org'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget.org'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '015fc12f-cd63-4ab4-8d6a-dc889e53bf70'
  - script: docfx
    displayName: Build DocFX
  - script: |
      set -eux
      ssh-keyscan -p 2222 192.168.0.21 >> ~/.ssh/known_hosts
      ssh -p 2222 lancer1977@192.168.0.21 "mkdir -p ${CDN_PATH}"      
      rsync -az --delete -e 'ssh -i ~/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=no' ./_site/ lancer1977@192.168.0.21:${CDN_PATH}/
  displayName: Deploy _site to CDN via rsync 